
hop_test:	hop_test.cc adsl-hop.cpp adsl-hop.h
	g++ -Wall -O2 -o hop_test hop_test.cc adsl-hop.cpp

hopping_3chan:	hopping_3chan.cc adsl-hop.cpp adsl-hop.h
	g++ -Wall -O2 -o hopping_3chan hopping_3chan.cc adsl-hop.cpp

hopping_2chan:	hopping_2chan.cc adsl-hop.cpp adsl-hop.h
	g++ -Wall -O2 -o hopping_2chan hopping_2chan.cc adsl-hop.pp

