hopping:	hopping.cc adsl-hop.cpp adsl-hop.h
	g++ -Wall -O2 -o hopping hopping.cc adsl-hop.cpp

hopping_mband:	hopping_mband.cc adsl-hop.cpp adsl-hop.h
	g++ -Wall -O2 -o hopping_mband hopping_mband.cc adsl-hop.cpp
